export const sampleData = [
  {
    id: 1,
    name: "sampleOne",
    description: "lorem ipsum dolor suite itter",
    available: true,
    price: 4000,
    inStock: 10,
    rating: 5,
    url: "/eccormerce/sampleOne.png",
  },
  {
    id: 2,
    name: "sampleTwo",
    description: "lorem ipsum dolor suite itter",
    available: true,
    price: 6000,
    inStock: 10,
    rating: 7,
    url: "/eccormerce/sampleTwo.png",
  },
  {
    id: 3,
    name: "sampleThree",
    description: "lorem ipsum dolor suite itter",
    available: true,
    price: 15000,
    inStock: 10,
    rating: 7,
    url: "/eccormerce/sampleThree.png",
  },
  {
    id: 4,
    name: "sampleFour",
    description: "lorem ipsum dolor suite itter",
    available: true,
    price: 15500,
    inStock: 10,
    rating: 2,
    url: "/eccormerce/sampleFour.png",
  },
  {
    id: 5,
    name: "sampleFive",
    description: "lorem ipsum dolor suite itter",
    available: true,
    price: 15000,
    inStock: 10,
    rating: 7,
    url: "/eccormerce/sampleFive.png",
  },
  {
    id: 6,
    name: "sampleSix",
    description: "lorem ipsum dolor suite itter",
    available: true,
    price: 15000,
    inStock: 10,
    rating: 7,
    url: "/eccormerce/sampleSix.png",
  },
];
